[project]
name = "ai-scraper-newsletter"
version = "0.1.0"
description = "AI scraper"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "orjson>=3.11.4",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
    "ruff>=0.14.7",
]
