urls: 
 - https://daringfireball.net
 - https://arstechnica.com
 - https://theregister.com
 - https://slashdot.org
 - https://lwn.net
 - https://hackernews.org
 - https://tomshardware.com
 - https://anandtech.com
 - https://phoronix.com
 - https://howtogeek.com
 - https://ghacks.net
 - https://osnews.com
 - https://betanews.com
 - https://techspot.com
 - https://neowin.net